# Generated by Django 3.2.5 on 2021-07-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('residence', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('occupation', models.CharField(max_length=150)),
                ('marital_status', models.CharField(max_length=50)),
                ('national_id', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'Records',
            },
        ),
    ]
